### ISSUE TITLE
Missing GPS Cable in BOM

### ISSUE THREAD

**Issue by keenanjohnson** [oceansystems/asv#1]
I believe the Bill of Materials is missing the Cable to Connect the GPS Module to the Pixhawk.

**Comment by keenanjohnson** [comment]
Not sure if anyone is maintaining this project or not, but I'm in the midst of trying to replicate the build.

The BOM only lists one of the MRC0203 cables, but I believe you need two for the GPS and the power module to connect to the pixhawk.

**Comment by drewjgray** [comment]
Thanks @keenanjohnson will take a look with @spiderkeys

**Comment by keenanjohnson** [comment]
Thanks! Out of curiosity, are you actively working on this project?

I'm interested in the state of the hull / solar panel design since I've actively building one and would rather work together to do that.

**Comment by keenanjohnson** [comment]
I sent an email to the contact email listed a while ago but never heard anything.

**Comment by spiderkeys** [comment]
Hi @keenanjohnson. The MRC0203 cable is, as you've identified, for the GPS<->Pixhawk connection. The power sense module comes with its own DF13-JST-GH cable, which is why only one is specified in the BOM.

The BOM calls out this particular component from Blue:
https://bluerobotics.com/store/comm-control-power/elec-packages/psm-asm-r2-rp/

If you scroll down and expand "Contents" under the product description, it lists both the module and 1 x 200mm DF13 to JST-GH cable.

Please let us know if you run into any more issues, find discrepancies in the docs, or require any clarifications and we will be happy to help (and get the docs updated!)

**Comment by drewjgray** [comment]
We are actively working on this project, but we are not currently manufacturing the hull we designed. If we get enough interest we may go ahead and make them. If we get there, we will definitely let you know!

**Comment by keenanjohnson** [comment]
That'd be great! In the meantime, is there any easy hull you would
recommend for testing?
